PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "links" (
    title       TEXT NOT NULL,
    url         TEXT NOT NULL UNIQUE,
    description TEXT
);

INSERT INTO links VALUES('0.30000000000000004','https://0.30000000000000004.com','Floating Point Math');
INSERT INTO links VALUES('404PageFound','https://www.404pagefound.com','Active vintage websites, old webpages and web 1.0');
INSERT INTO links VALUES('500 Mile Email','https://500mile.email','A curated list of absurd software bug stories');
INSERT INTO links VALUES('8bitworkshop','https://8bitworkshop.com','Write 8-bit code in your browser');
INSERT INTO links VALUES('Active GitHub Forks','https://techgaun.github.io/active-forks',NULL);
INSERT INTO links VALUES('American Philatelic Society','https://stamps.org/',NULL);
INSERT INTO links VALUES('Aminet','https://aminet.net','A set of interconnected WWW and FTP servers hosting freely distributable Amiga software');
INSERT INTO links VALUES('An Illustrated Guide to IPsec','http://unixwiz.net/techtips/iguide-ipsec.html',NULL);
INSERT INTO links VALUES('An incomplete history of the QED Text Editor','https://www.bell-labs.com/usr/dmr/www/qed.html',NULL);
INSERT INTO links VALUES('An Interactive Introduction to Fourier Transforms','https://www.jezzamon.com/fourier/',NULL);
INSERT INTO links VALUES('Angry Reviewer','https://www.angryreviewer.com','Academic style corrector for scientific writing');
INSERT INTO links VALUES('AniCheck','https://anicheck.moe/',NULL);
INSERT INTO links VALUES('Animelon','https://animelon.com','Learn Japanese while watching anime with Japanese, English and romanized subtitles');
INSERT INTO links VALUES('Artificial Life Portal','http://en.alife.pl/main/e','Collection of interesting projects at the intersection of computer science, biology, physics and art');
INSERT INTO links VALUES('ASCIIFlow','https://asciiflow.com/',NULL);
INSERT INTO links VALUES('Atarimania','http://www.atarimania.com',NULL);
INSERT INTO links VALUES('Backwards Compatibilty Chart','https://docs.google.com/spreadsheets/d/13BnuFlQUVbxLMYRO5Ms8TUhbiefmXsUE69OYVwp1mZ0','Check which game systems are backward compatible');
INSERT INTO links VALUES('Big Book of Amiga Hardware','https://bigbookofamigahardware.com',NULL);
INSERT INTO links VALUES('Big-O Algorithm Complexity Cheat Sheet (Know Thy Complexities!)','https://www.bigocheatsheet.com/',NULL);
INSERT INTO links VALUES('C64 Power','http://c64power.com/','Kompendium Wiedzy o komputerze Commodore 64');
INSERT INTO links VALUES('Carbon','https://carbon.now.sh','Create image of source code');
INSERT INTO links VALUES('Chmod Calculator','https://chmodcommand.com',NULL);
INSERT INTO links VALUES('Choose an open source license','https://choosealicense.com',NULL);
INSERT INTO links VALUES('chubin/awesome-console-services','https://github.com/chubin/awesome-console-services','Console services reachable via network protocols');
INSERT INTO links VALUES('Circuit Simulator Applet','http://www.falstad.com/circuit/',NULL);
INSERT INTO links VALUES('CiteThis','https://citethis.net',NULL);
INSERT INTO links VALUES('Colobot','https://colobot.info','A (fun!) educational game where you can program bots to find a new planet to live and survive');
INSERT INTO links VALUES('Computer Science Field Guide','https://csfieldguide.org.nz',NULL);
INSERT INTO links VALUES('Consolevariations.com','https://consolevariations.com/',NULL);
INSERT INTO links VALUES('CppQuiz','http://cppquiz.org',NULL);
INSERT INTO links VALUES('crontab guru','https://crontab.guru','Simple editor for cron schedule expressions');
INSERT INTO links VALUES('CSS Gradient','https://cssgradient.io','Generator of CSS rule with gradient background');
INSERT INTO links VALUES('CTAN','https://ctan.org/','The Comprehensive TeX Archive Network');
INSERT INTO links VALUES('Czarna lista zasilaczy i Renomowane marki zasilaczy','https://www.elektroda.pl/rtvforum/topic1199271.html',NULL);
INSERT INTO links VALUES('dCode','https://www.dcode.fr/en','A collection of over 800 tools to help solve games, riddles, ciphers, mathematics, puzzles, etc.');
INSERT INTO links VALUES('Decompiler Explorer','https://dogbolt.org/',NULL);
INSERT INTO links VALUES('Denigma','https://denigma.app/','AI that reads and explains code in English');
INSERT INTO links VALUES('Dennis Ritchie Thesis – And the Typewriting Devices in the 1960s','https://dmrthesis.net/',NULL);
INSERT INTO links VALUES('Detexify','http://detexify.kirelabs.org/classify.html','LaTeX handwritten symbol recognition');
INSERT INTO links VALUES('Diagon','https://arthursonzogni.com/Diagon/','Interactive ASCII art diagram collection');
INSERT INTO links VALUES('DistroSea','https://distrosea.com/',NULL);
INSERT INTO links VALUES('Donut math: how donut.c works','https://www.a1k0n.net/2011/07/20/donut-math.html',NULL);
INSERT INTO links VALUES('Down For Everyone Or Just Me','https://downforeveryoneorjustme.com',NULL);
INSERT INTO links VALUES('Dr Chip''s Vim Page','http://www.drchip.org/astronaut/vim/index.html',NULL);
INSERT INTO links VALUES('Electron Band Structure In Germanium, My Ass','http://pages.cs.wisc.edu/~kovar/hall.html',NULL);
INSERT INTO links VALUES('Electronic Handheld Game Museum','https://www.handheldmuseum.com/',NULL);
INSERT INTO links VALUES('ELMak''s Remote Control Search','https://wyszukiwarka.elmak.pl',NULL);
INSERT INTO links VALUES('Emperor Sh and the Traveller','https://sanctum.geek.nz/etc/emperor-sh-and-the-traveller.txt',NULL);
INSERT INTO links VALUES('Everything Amiga','https://www.everythingamiga.com',NULL);
INSERT INTO links VALUES('EXPONET','http://www.exponet.info/index.php?lng=EN','Virtual international philatelic exhibition');
INSERT INTO links VALUES('Fantasy Name Generators','https://www.fantasynamegenerators.com',NULL);
INSERT INTO links VALUES('Feed Creator','http://createfeed.fivefilters.org',NULL);
INSERT INTO links VALUES('FilterLists','https://filterlists.com',NULL);
INSERT INTO links VALUES('Flexbox Froggy','https://flexboxfroggy.com','A game for learning CSS flexbox');
INSERT INTO links VALUES('Free AI Video Upscaler','https://free.upscaler.video/',NULL);
INSERT INTO links VALUES('GamingOnLinux','https://www.gamingonlinux.com',NULL);
INSERT INTO links VALUES('gbdev','https://gbdev.io',NULL);
INSERT INTO links VALUES('gifcap','https://gifcap.dev/',NULL);
INSERT INTO links VALUES('git rebase in depth','https://git-rebase.io',NULL);
INSERT INTO links VALUES('GNU Assembler Examples','https://cs.lmu.edu/%7Eray/notes/gasexamples/',NULL);
INSERT INTO links VALUES('GoF design patterns quiz','http://www.vincehuston.org/dp/patterns_quiz.html','Recognize pattern based on UML diagram (and the intent)');
INSERT INTO links VALUES('Haifux - The Haifa Linux club','http://www.haifux.org/',NULL);
INSERT INTO links VALUES('Heavens-Above','https://www.heavens-above.com','Satellite predictions and other astronomical data customised for your location');
INSERT INTO links VALUES('Help Vampires: A Spotter’s Guide','https://slash7.com/2006/12/22/vampires/',NULL);
INSERT INTO links VALUES('Help! Linux ate my RAM!','https://www.linuxatemyram.com/',NULL);
INSERT INTO links VALUES('Hidden Palace','http://hiddenpalace.org','Community dedicated to the preservation of video game development media');
INSERT INTO links VALUES('Hiragana Quiz','https://hiraganaquiz.com/',NULL);
INSERT INTO links VALUES('How can I handle command-line options and arguments in my script easily?','https://mywiki.wooledge.org/BashFAQ/035',NULL);
INSERT INTO links VALUES('How Java’s Floating-Point Hurts Everyone Everywhere','https://people.eecs.berkeley.edu/~wkahan/JAVAhurt.pdf',NULL);
INSERT INTO links VALUES('How To Ask Questions The Smart Way','http://www.catb.org/%7Eesr/faqs/smart-questions.html',NULL);
INSERT INTO links VALUES('How to Use the Coffee Taster''s Flavor Wheel in 8 Steps','https://scanews.coffee/2016/02/05/how-to-use-the-coffee-tasters-flavor-wheel-in-8-steps/',NULL);
INSERT INTO links VALUES('HyperPhysics','http://hyperphysics.phy-astr.gsu.edu/hbase',NULL);
INSERT INTO links VALUES('Hyrum''s Law','https://www.hyrumslaw.com/',NULL);
INSERT INTO links VALUES('I downvoted because...','https://idownvotedbecau.se/',NULL);
INSERT INTO links VALUES('If the Moon Were Only 1 Pixel','https://joshworth.com/dev/pixelspace/','A tediously accurate map of the solar system');
INSERT INTO links VALUES('ImprovMX','https://improvmx.com/','Email forwarding, email aliases for your domain name.');
INSERT INTO links VALUES('Index of reviewed multimeters table','https://lygte-info.dk/info/DMMReviews.html',NULL);
INSERT INTO links VALUES('Internet Explorer is EVIL!','http://toastytech.com/evil/index.html',NULL);
INSERT INTO links VALUES('IntroARM','https://opensecuritytraining.info/IntroARM.html',NULL);
INSERT INTO links VALUES('ircdocs.horse','https://ircdocs.horse','Information and documentation about the IRC protocol');
INSERT INTO links VALUES('Kanshudo','https://www.kanshudo.com',NULL);
INSERT INTO links VALUES('Katalog Znaków Pocztowych','https://www.kzp.pl',NULL);
INSERT INTO links VALUES('Keep a Changelog','https://keepachangelog.com',NULL);
INSERT INTO links VALUES('Kill the Newsletter!','https://kill-the-newsletter.com/',NULL);
INSERT INTO links VALUES('kitsunekko - Japanese subtitles','http://kitsunekko.net/dirlist.php?dir=subtitles%2Fjapanese%2F',NULL);
INSERT INTO links VALUES('Langserver.org','https://langserver.org/',NULL);
INSERT INTO links VALUES('LCDMOD','http://neslcdmod.com',NULL);
INSERT INTO links VALUES('Learn C++','https://www.learncpp.com',NULL);
INSERT INTO links VALUES('Learning COBOL: A Journey for the Modern Programmer','https://monadical.com/posts/cobol.html',NULL);
INSERT INTO links VALUES('Legends of Localization','https://legendsoflocalization.com','The Legends of Localization series takes a look at video game translation and how games change during the translation process');
INSERT INTO links VALUES('Lemon Amiga','https://www.lemonamiga.com',NULL);
INSERT INTO links VALUES('Libregamewiki','https://libregamewiki.org',NULL);
INSERT INTO links VALUES('Line of Action','https://line-of-action.com',NULL);
INSERT INTO links VALUES('Linux Font Equivalents to Popular Web Typefaces','https://jonchristopher.us/blog/linux-font-equivalents-to-popular-web-typefaces/',NULL);
INSERT INTO links VALUES('Linux Journey','https://linuxjourney.com',NULL);
INSERT INTO links VALUES('Logically Fallacious','https://www.logicallyfallacious.com',NULL);
INSERT INTO links VALUES('LOW-TECH MAGAZINE','https://www.lowtechmagazine.com',NULL);
INSERT INTO links VALUES('Manifesto for Software Craftsmanship','https://manifesto.softwarecraftsmanship.org/',NULL);
INSERT INTO links VALUES('Map of Biology','https://flic.kr/p/CF9wte',NULL);
INSERT INTO links VALUES('Map of Chemistry','https://flic.kr/p/UNA1LW',NULL);
INSERT INTO links VALUES('Map of Computer Science','https://flic.kr/p/XcFBKC',NULL);
INSERT INTO links VALUES('Map of Mathematics','https://flic.kr/p/RXdRRd',NULL);
INSERT INTO links VALUES('Map of Physics','https://flic.kr/p/Pcj581',NULL);
INSERT INTO links VALUES('MARC: Mailing list ARChives','https://marc.info/','');
INSERT INTO links VALUES('Motherboard.cz','http://www.motherboard.cz',NULL);
INSERT INTO links VALUES('Musicca','https://www.musicca.com','Lessons, exercises, and interactive tools that help learn music');
INSERT INTO links VALUES('NA » NES Programming','http://archive.nes.science/nintendoage-forums/nintendoage.com/forum/messageviewadfa.html?catid=22&threadid=7155',NULL);
INSERT INTO links VALUES('nand2tetris','https://www.nand2tetris.org',NULL);
INSERT INTO links VALUES('NandGame','http://nandgame.com/','Build a computer from scratch');
INSERT INTO links VALUES('NASM Assembly Language Tutorials - asmtutor.com','https://asmtutor.com',NULL);
INSERT INTO links VALUES('ncurses wrappers for C++','https://www.reversed.top/2016-04-24/ncurses-for-cpp/',NULL);
INSERT INTO links VALUES('netsplit.de','https://netsplit.de/','IRC search engine');
INSERT INTO links VALUES('Novel Updates','https://www.novelupdates.com',NULL);
INSERT INTO links VALUES('OLD-COMPUTERS.COM','https://www.old-computers.com/museum/default.asp',NULL);
INSERT INTO links VALUES('OldGames.sk','https://www.oldgames.sk/en',NULL);
INSERT INTO links VALUES('OldWeb.Today','https://oldweb.today',NULL);
INSERT INTO links VALUES('Open Source Game Clones','https://osgameclones.com',NULL);
INSERT INTO links VALUES('OpenGameArt.org','https://opengameart.org','Free, legal art for Open Source game projects');
INSERT INTO links VALUES('OpenRetro Game Database','https://openretro.org',NULL);
INSERT INTO links VALUES('Oscar Forner - Sorting algorithms','https://oscarforner.com/blog/2020-02-10-sorting-algorithms/',NULL);
INSERT INTO links VALUES('Oscilloscope Music','https://oscilloscopemusic.com',NULL);
INSERT INTO links VALUES('OSDev.org','https://wiki.osdev.org/Main_Page',NULL);
INSERT INTO links VALUES('Packaging Python Projects','https://packaging.python.org/tutorials/packaging-projects/#packaging-your-project',NULL);
INSERT INTO links VALUES('Paletton','https://paletton.com','Color scheme designer');
INSERT INTO links VALUES('Papers We Love','https://paperswelove.org',NULL);
INSERT INTO links VALUES('Paywall Reader','https://paywallreader.com','');
INSERT INTO links VALUES('PCjs Machines','https://www.pcjs.org/',NULL);
INSERT INTO links VALUES('PDF24 Tools','https://tools.pdf24.org/en/',NULL);
INSERT INTO links VALUES('PlantText UML Editor','https://www.planttext.com/',NULL);
INSERT INTO links VALUES('PlantUML','https://plantuml.com/',NULL);
INSERT INTO links VALUES('playlist.tools','https://playlist.tools','Reverse YouTube Playlists and more');
INSERT INTO links VALUES('PolitePol','https://politepol.com',NULL);
INSERT INTO links VALUES('POSIX Shell Utilities','https://pubs.opengroup.org/onlinepubs/9699919799/idx/utilities.html',NULL);
INSERT INTO links VALUES('Power Thesaurus','https://www.powerthesaurus.org/',NULL);
INSERT INTO links VALUES('PPA','https://www.ppa.pl','Polski Portal Amigowy');
INSERT INTO links VALUES('ProofWiki','https://proofwiki.org/wiki/Main_Page',NULL);
INSERT INTO links VALUES('ProtonDB','https://www.protondb.com',NULL);
INSERT INTO links VALUES('Real Kana','https://realkana.com',NULL);
INSERT INTO links VALUES('Real Kanji','https://realkanji.com/',NULL);
INSERT INTO links VALUES('Refactoring.Guru','https://refactoring.guru',NULL);
INSERT INTO links VALUES('regex101','https://regex101.com',NULL);
INSERT INTO links VALUES('Regular-Expressions.info','https://www.regular-expressions.info',NULL);
INSERT INTO links VALUES('Retro Redrawn','https://retroredrawn.com','Pixel-art remakes and demakes of game graphics');
INSERT INTO links VALUES('retrokolekcja.pl','http://retrokolekcja.pl','Muzeum polskich półprzewodników i elementów hybrydowych');
INSERT INTO links VALUES('ReviewMeta','https://reviewmeta.com','Identifying fake Amazon reviews');
INSERT INTO links VALUES('Rook Polynomials (Darryl K. Nester, Bluffton University)','https://homepages.bluffton.edu/~nesterd/apps/rookpolynomials.html',NULL);
INSERT INTO links VALUES('Rozwiązania zadań ze zbioru Mendela cz. 1','http://www.pracadomowa.pl/ksiazka/zbior-zadan-z-fizyki-dla-klasy-i-szkol-srednich',NULL);
INSERT INTO links VALUES('RSS-Bridge/rss-bridge','https://github.com/RSS-Bridge/rss-bridge',NULL);
INSERT INTO links VALUES('SailRabbit','https://www.sailrabbit.com/bmr/','Basal Metabolic Rate (BMR) and Total Daily Energy Expenditure (TDEE) Calculator');
INSERT INTO links VALUES('Satori Reader','https://www.satorireader.com',NULL);
INSERT INTO links VALUES('SauceNAO','https://saucenao.com',NULL);
INSERT INTO links VALUES('Semantic Versioning','https://semver.org',NULL);
INSERT INTO links VALUES('Shooting yourself in the foot in various programming languages','http://www.toodarkpark.org/computers/humor/shoot-self-in-foot.html',NULL);
INSERT INTO links VALUES('siftrss','https://siftrss.com/','Filter RSS feed');
INSERT INTO links VALUES('Snappy Driver Installer Origin','https://www.snappy-driver-installer.org/','Portable driver installation and update tool (for old Windows)');
INSERT INTO links VALUES('Snaptron''s design guide','https://go.snaptron.com/design-guide-v3.0','Engineering handbook for metal dome switch design');
INSERT INTO links VALUES('Software optimization resources','https://www.agner.org/optimize',NULL);
INSERT INTO links VALUES('Software Package Data Exchange','https://spdx.dev','SPDX');
INSERT INTO links VALUES('Software Preservation Group','https://www.softwarepreservation.org/',NULL);
INSERT INTO links VALUES('Sprout Anime Recommender','https://anime.ameo.dev/',NULL);
INSERT INTO links VALUES('Spurious Correlations','https://tylervigen.com/spurious-correlations',NULL);
INSERT INTO links VALUES('SQLBolt','https://sqlbolt.com/','A series of interactive lessons and exercises designed for learning SQL right in browser');
INSERT INTO links VALUES('SQLite C tutorial','https://zetcode.com/db/sqlitec/',NULL);
INSERT INTO links VALUES('Steam Calculator','https://steamdb.info/calculator',NULL);
INSERT INTO links VALUES('Stemplowanie i kasowanie, czyli o pieczątkach w filatelistyce','http://www.stampler.pl/porady,stemplowanie',NULL);
INSERT INTO links VALUES('Tables Generator','https://www.tablesgenerator.com',NULL);
INSERT INTO links VALUES('Teach Yourself Computer Science','https://teachyourselfcs.com/',NULL);
INSERT INTO links VALUES('Teach Yourself Programming in Ten Years','https://norvig.com/21-days.html',NULL);
INSERT INTO links VALUES('Terms of Service; Didn''t Read','https://tosdr.org/',NULL);
INSERT INTO links VALUES('TeX Live documentation','https://tug.org/texlive/Contents/live/doc.html',NULL);
INSERT INTO links VALUES('TeXdoc Online','https://texdoc.net/',NULL);
INSERT INTO links VALUES('Text to ASCII Art Generator (TAAG)','http://www.patorjk.com/software/taag','Nice fonts: ANSI Shadow, Broadway KB, Mini');
INSERT INTO links VALUES('Textcraft','https://textcraft.net','Text & logo maker - Minecraft, 8-bit styles and more');
INSERT INTO links VALUES('Textik','https://textik.com','ASCII diagrams editor');
INSERT INTO links VALUES('The Amiga Museum','https://theamigamuseum.com',NULL);
INSERT INTO links VALUES('The Best Motherfucking Website','https://thebestmotherfucking.website',NULL);
INSERT INTO links VALUES('The Grind Size Chart - My no BS* guide to GRINDING','https://coffeechronicler.com/grind-size-chart',NULL);
INSERT INTO links VALUES('The Grymoire','https://www.grymoire.com',NULL);
INSERT INTO links VALUES('The IUPAC Compendium of Chemical Terminology','https://goldbook.iupac.org/',NULL);
INSERT INTO links VALUES('The On-Line Encyclopedia of Integer Sequences (OEIS)','https://oeis.org/',NULL);
INSERT INTO links VALUES('The Open Group Base Specifications Issue 7, 2018 edition - Environment Variables','https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html',NULL);
INSERT INTO links VALUES('The Problem with Time & Timezones','https://www.youtube.com/watch?v=-5wpm-gesOY',NULL);
INSERT INTO links VALUES('The SEGA Hardware Database','https://hardware.segakore.fr/en/',NULL);
INSERT INTO links VALUES('The Ultimate Oldschool PC Font Pack','https://int10h.org/oldschool-pc-fonts',NULL);
INSERT INTO links VALUES('TLD-List','https://tld-list.com','Compare prices of all Top-Level Domains');
INSERT INTO links VALUES('Turing Complete','https://wiki.c2.com/?TuringComplete',NULL);
INSERT INTO links VALUES('Turing machine visualization','https://turingmachine.io/',NULL);
INSERT INTO links VALUES('Two-Bit History','https://twobithistory.org',NULL);
INSERT INTO links VALUES('Unix ASCII games | awesome-ttygames','https://ligurio.github.io/awesome-ttygames',NULL);
INSERT INTO links VALUES('Unseen64','https://www.unseen64.net','Cancelled Video Games & Their Lost Media');
INSERT INTO links VALUES('Untrusted','https://alexnisnevich.github.io/untrusted/','JavaScript adventure game');
INSERT INTO links VALUES('Upgrade Amiga 500 rev. 8a board to Amiga 500+','https://www.tsb.space/bl0g/upgrade-amiga-500-rev-8a-board-to-amiga-500/',NULL);
INSERT INTO links VALUES('Use plain text email','https://useplaintext.email/',NULL);
INSERT INTO links VALUES('userChrome.css for Customizing Firefox','https://www.userchrome.org/',NULL);
INSERT INTO links VALUES('Video Game Console Library','https://www.videogameconsolelibrary.com/',NULL);
INSERT INTO links VALUES('Vintage BASIC','http://www.vintage-basic.net',NULL);
INSERT INTO links VALUES('WAIT: What Anime Is This?','https://trace.moe',NULL);
INSERT INTO links VALUES('WaniKani','https://www.wanikani.com',NULL);
INSERT INTO links VALUES('Wat','https://www.destroyallsoftware.com/talks/wat','Few examples of weird quirks of Ruby and JS');
INSERT INTO links VALUES('What every programmer should know about memory, Part 1 [LWN.net]','https://lwn.net/Articles/250967/',NULL);
INSERT INTO links VALUES('Word Cloud Generator','https://www.jasondavies.com/wordcloud/',NULL);
INSERT INTO links VALUES('World Stamp Catalogues','https://www.worldstampcatalogues.com/',NULL);
INSERT INTO links VALUES('Zapach papieru','https://zapach-papieru.pl','Strona fanów prasy o grach');
INSERT INTO links VALUES('青空文庫','https://www.aozora.gr.jp','Classic Japanese novels for free');

-- INSERT INTO links VALUES('','','');

COMMIT;
