name: Update DB

on:
  push:
    branches: [ database ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update
      run: |
        python3 insert.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update
        branch: database
